package:
  name: contour-1.29
  version: 1.29.1
  epoch: 1
  description: Contour is a Kubernetes ingress controller using Envoy proxy.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - contour=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/projectcontour/contour
      tag: v${{package.version}}
      expected-commit: be445838b789500b1ef4241b61d96afc3316989e

  - uses: go/build
    with:
      packages: ./cmd/contour
      output: contour
      ldflags: |
        -s -w
        -X github.com/projectcontour/contour/internal/build.Version=${{package.version}}
        -X github.com/projectcontour/contour/internal/build.Sha=$(git rev-parse HEAD)
        -X github.com/projectcontour/contour/internal/build.Branch=$(git rev-parse --abbrev-ref HEAD)

  - uses: strip

update:
  enabled: true
  github:
    identifier: projectcontour/contour
    strip-prefix: v
    tag-filter: v1.29.

test:
  pipeline:
    - runs: |
        contour version
