package:
  name: elixir-1.17
  version: 1.17.0
  epoch: 0
  description: General-purpose programming language and runtime environment
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - erlang
    provides:
      - elixir=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - erlang
      - erlang-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0b8623a032555d77cbd7cba815736b0ca1335e51
      repository: https://github.com/elixir-lang/elixir
      tag: v${{package.version}}

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: elixir-lang/elixir
    strip-prefix: v
    tag-filter-prefix: v1.17

test:
  pipeline:
    - runs: |
        elixir --version

        cat <<'EOF' >> /tmp/hello.exs
        IO.puts("Hello, Wolfi!")
        EOF

        elixir /tmp/hello.exs
