package:
  name: grype
  version: 0.79.0
  epoch: 0
  description: Vulnerability scanner for container images, filesystems, and SBOMs
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/anchore/grype
      tag: v${{package.version}}
      expected-commit: 5821351240dab7145f7cdd156f6a1ecf88cf8da7

  - uses: go/build
    with:
      ldflags: -X main.version=${{package.version}}
      output: grype
      packages: ./cmd/grype

  - uses: strip

update:
  enabled: true
  github:
    identifier: anchore/grype
    strip-prefix: v

test:
  pipeline:
    - runs: |
        grype --version
