package:
  name: neuvector-nstools
  version: 5.3.3
  epoch: 0
  description: "NeuVector NSTools"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6b3d5a2e725648ef13f913e403e9e5b955d8c7ef
      repository: https://github.com/neuvector/neuvector.git
      tag: v${{package.version}}

  - runs: |
      make -C tools/nstools
      mkdir -p ${{targets.contextdir}}/usr/local/bin
      install -Dm755 tools/nstools/nstools ${{targets.contextdir}}/usr/local/bin/nstools

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\-.*'
  github:
    identifier: neuvector/neuvector
    strip-prefix: v

test:
  pipeline:
    - name: Run Help Command
      runs: |
        /usr/local/bin/nstools | grep 'h: help'
